export const GET_ALL_ABILITY_REQUEST = 'GET_ALL_ABILITY_REQUEST'
export const GET_ALL_ABILITY_SUCCESS = 'GET_ALL_ABILITY_SUCCESS'
export const GET_ALL_ABILITY_FAIL = 'GET_ALL_ABILITY_FAIL'


export const ADD_ABILITY_TO_PERSON_REQUEST = 'ADD_ABILITY_TO_PERSON_REQUEST'
export const ADD_ABILITY_TO_PERSON_SUCCESS = 'ADD_ABILITY_TO_PERSON_SUCCESS'
export const ADD_ABILITY_TO_PERSON_FAIL = 'ADD_ABILITY_TO_PERSON_FAIL'

export const ADD_ABILITY_REQUEST = 'ADD_ABILITY_REQUEST'
export const ADD_ABILITY_SUCCESS = 'ADD_ABILITY_SUCCESS'
export const ADD_ABILITY_FAIL = 'ADD_ABILITY_FAIL'
export const ADD_ABILITY_RESET = 'ADD_ABILITY_RESET'


export const DELETE_ABILITY_REQUEST = 'DELETE_ABILITY_REQUEST'
export const DELETE_ABILITY_SUCCESS = 'DELETE_ABILITY_SUCCESS'
export const DELETE_ABILITY_FAIL = 'DELETE_ABILITY_FAIL'
export const DELETE_ABILITY_RESET = 'DELETE_ABILITY_RESET'

export const UPDATE_ABILITY_REQUEST = 'UPDATE_ABILITY_REQUEST'
export const UPDATE_ABILITY_SUCCESS = 'UPDATE_ABILITY_SUCCESS'
export const UPDATE_ABILITY_FAIL = 'UPDATE_ABILITY_FAIL'
export const UPDATE_ABILITY_RESET = 'UPDATE_ABILITY_RESET'