export const GET_ALL_PERSON_REQUEST = 'GET_ALL_PERSON_REQUEST'
export const GET_ALL_PERSON_SUCCESS = 'GET_ALL_PERSON_SUCCESS'
export const GET_ALL_PERSON_FAIL = 'GET_ALL_PERSON_FAIL'

export const ADD_NEW_PERSON_REQUEST = 'ADD_NEW_PERSON_REQUEST'
export const ADD_NEW_PERSON_SUCCESS = 'ADD_NEW_PERSON_SUCCESS'
export const ADD_NEW_PERSON_FAIL = 'ADD_NEW_PERSON_FAIL'
export const ADD_NEW_PERSON_RESET = 'ADD_NEW_PERSON_RESET'

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST'
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS'
export const DELETE_PERSON_FAIL = 'DELETE_PERSON_FAIL'
export const DELETE_PERSON_RESET = 'DELETE_PERSON_RESET'

export const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST'
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS'
export const UPDATE_PERSON_FAIL = 'UPDATE_PERSON_FAIL'
export const UPDATE_PERSON_RESET = 'UPDATE_PERSON_RESET'

export const GET_PERSON_DETAILS_REQUEST = 'GET_PERSON_DETAILS_REQUEST'
export const GET_PERSON_DETAILS_SUCCESS = 'GET_PERSON_DETAILS_SUCCESS'
export const GET_PERSON_DETAILS_FAIL = 'GET_PERSON_DETAILS_FAIL'


export const ADD_SKILL_TO_PERSON_REQUEST = 'ADD_SKILL_TO_PERSON_REQUEST'
export const ADD_SKILL_TO_PERSON_SUCCESS = 'ADD_SKILL_TO_PERSON_SUCCESS'
export const ADD_SKILL_TO_PERSON_FAIL = 'ADD_SKILL_TO_PERSON_FAIL'
export const ADD_SKILL_TO_PERSON_RESET = 'ADD_SKILL_TO_PERSON_RESET'